version: '3.7'
services:
  database:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: techwall
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_techwall
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
