

GET {{hostname}}

###

GET {{hostname}}/todo


###

GET {{hostname}}/todo/5
###

POST {{hostname}}/todo
Content-Type: application/json

{
    "name":"second Todo",
    "description":"mon second Todo"
}

###
PUT {{hostname}}/todo

###
DELETE {{hostname}}/todo